# Generated by Django 4.1.4 on 2022-12-17 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_roles_customuser_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='code_employee',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
