# Generated by Django 4.1.4 on 2022-12-22 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_codesverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codesverification',
            name='changePasswordCode',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
