# Generated by Django 4.1.4 on 2022-12-21 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_alter_payroll_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='url_payroll',
            field=models.URLField(null=True),
        ),
    ]
