# Generated by Django 4.1.4 on 2022-12-22 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_payroll_url_payroll'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payroll',
            name='url_payroll',
        ),
    ]
